-- Menyesuaikan struktur tabel pendaftaran dengan field Orang Tua/Wali pada formulir.
-- Kolom lama ortu_* tetap dipertahankan untuk kompatibilitas cetak/export lama.

ALTER TABLE `pendaftaran`
  ADD COLUMN IF NOT EXISTS `nama_ayah` varchar(120) DEFAULT NULL AFTER `ortu_alamat`,
  ADD COLUMN IF NOT EXISTS `nik_ayah` varchar(20) DEFAULT NULL AFTER `nama_ayah`,
  ADD COLUMN IF NOT EXISTS `tempat_lahir_ayah` varchar(80) DEFAULT NULL AFTER `nik_ayah`,
  ADD COLUMN IF NOT EXISTS `tanggal_lahir_ayah` varchar(20) DEFAULT NULL AFTER `tempat_lahir_ayah`,
  ADD COLUMN IF NOT EXISTS `agama_ayah` varchar(30) DEFAULT NULL AFTER `tanggal_lahir_ayah`,
  ADD COLUMN IF NOT EXISTS `pendidikan_ayah` varchar(30) DEFAULT NULL AFTER `agama_ayah`,
  ADD COLUMN IF NOT EXISTS `hp_ayah` varchar(30) DEFAULT NULL AFTER `pendidikan_ayah`,
  ADD COLUMN IF NOT EXISTS `pekerjaan_ayah` varchar(120) DEFAULT NULL AFTER `hp_ayah`,
  ADD COLUMN IF NOT EXISTS `penghasilan_ayah` varchar(80) DEFAULT NULL AFTER `pekerjaan_ayah`,
  ADD COLUMN IF NOT EXISTS `nama_ibu` varchar(120) DEFAULT NULL AFTER `penghasilan_ayah`,
  ADD COLUMN IF NOT EXISTS `nik_ibu` varchar(20) DEFAULT NULL AFTER `nama_ibu`,
  ADD COLUMN IF NOT EXISTS `tempat_lahir_ibu` varchar(80) DEFAULT NULL AFTER `nik_ibu`,
  ADD COLUMN IF NOT EXISTS `tanggal_lahir_ibu` varchar(20) DEFAULT NULL AFTER `tempat_lahir_ibu`,
  ADD COLUMN IF NOT EXISTS `agama_ibu` varchar(30) DEFAULT NULL AFTER `tanggal_lahir_ibu`,
  ADD COLUMN IF NOT EXISTS `pendidikan_ibu` varchar(30) DEFAULT NULL AFTER `agama_ibu`,
  ADD COLUMN IF NOT EXISTS `hp_ibu` varchar(30) DEFAULT NULL AFTER `pendidikan_ibu`,
  ADD COLUMN IF NOT EXISTS `pekerjaan_ibu` varchar(120) DEFAULT NULL AFTER `hp_ibu`,
  ADD COLUMN IF NOT EXISTS `penghasilan_ibu` varchar(80) DEFAULT NULL AFTER `pekerjaan_ibu`,
  ADD COLUMN IF NOT EXISTS `alamat_orang_tua` text NULL AFTER `penghasilan_ibu`,
  ADD COLUMN IF NOT EXISTS `nama_wali` varchar(120) DEFAULT NULL AFTER `alamat_orang_tua`,
  ADD COLUMN IF NOT EXISTS `nik_wali` varchar(20) DEFAULT NULL AFTER `nama_wali`,
  ADD COLUMN IF NOT EXISTS `tempat_lahir_wali` varchar(80) DEFAULT NULL AFTER `nik_wali`,
  ADD COLUMN IF NOT EXISTS `tanggal_lahir_wali` varchar(20) DEFAULT NULL AFTER `tempat_lahir_wali`,
  ADD COLUMN IF NOT EXISTS `agama_wali` varchar(30) DEFAULT NULL AFTER `tanggal_lahir_wali`,
  ADD COLUMN IF NOT EXISTS `pendidikan_wali` varchar(30) DEFAULT NULL AFTER `agama_wali`,
  ADD COLUMN IF NOT EXISTS `hp_wali` varchar(30) DEFAULT NULL AFTER `pendidikan_wali`,
  ADD COLUMN IF NOT EXISTS `pekerjaan_wali` varchar(120) DEFAULT NULL AFTER `hp_wali`,
  ADD COLUMN IF NOT EXISTS `penghasilan_wali` varchar(80) DEFAULT NULL AFTER `pekerjaan_wali`,
  ADD COLUMN IF NOT EXISTS `alamat_wali` text NULL AFTER `penghasilan_wali`;

UPDATE `pendaftaran`
SET
  `nama_ayah` = COALESCE(NULLIF(`nama_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_nama`, ',', 1)), '-'), '0')),
  `nama_ibu` = COALESCE(NULLIF(`nama_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_nama`, ',', 2), ',', -1)), '-'), '0')),
  `nama_wali` = COALESCE(NULLIF(`nama_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_nama`, ',', -1)), '-'), '0')),
  `nik_ayah` = COALESCE(NULLIF(`nik_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_nik`, ',', 1)), '-'), '0')),
  `nik_ibu` = COALESCE(NULLIF(`nik_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_nik`, ',', 2), ',', -1)), '-'), '0')),
  `nik_wali` = COALESCE(NULLIF(`nik_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_nik`, ',', -1)), '-'), '0')),
  `tempat_lahir_ayah` = COALESCE(NULLIF(`tempat_lahir_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_tempat_lahir`, '|', 1)), '-'), '0')),
  `tempat_lahir_ibu` = COALESCE(NULLIF(`tempat_lahir_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_tempat_lahir`, '|', 2), '|', -1)), '-'), '0')),
  `tempat_lahir_wali` = COALESCE(NULLIF(`tempat_lahir_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_tempat_lahir`, '|', -1)), '-'), '0')),
  `tanggal_lahir_ayah` = COALESCE(NULLIF(`tanggal_lahir_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_tgl_lahir`, '|', 1)), '-'), '0')),
  `tanggal_lahir_ibu` = COALESCE(NULLIF(`tanggal_lahir_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_tgl_lahir`, '|', 2), '|', -1)), '-'), '0')),
  `tanggal_lahir_wali` = COALESCE(NULLIF(`tanggal_lahir_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_tgl_lahir`, '|', -1)), '-'), '0')),
  `agama_ayah` = COALESCE(NULLIF(`agama_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_agama`, ',', 1)), '-'), '0')),
  `agama_ibu` = COALESCE(NULLIF(`agama_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_agama`, ',', 2), ',', -1)), '-'), '0')),
  `agama_wali` = COALESCE(NULLIF(`agama_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_agama`, ',', -1)), '-'), '0')),
  `pendidikan_ayah` = COALESCE(NULLIF(`pendidikan_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_pendidikan`, ',', 1)), '-'), '0')),
  `pendidikan_ibu` = COALESCE(NULLIF(`pendidikan_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_pendidikan`, ',', 2), ',', -1)), '-'), '0')),
  `pendidikan_wali` = COALESCE(NULLIF(`pendidikan_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_pendidikan`, ',', -1)), '-'), '0')),
  `hp_ayah` = COALESCE(NULLIF(`hp_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_hp`, ',', 1)), '-'), '0')),
  `hp_ibu` = COALESCE(NULLIF(`hp_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_hp`, ',', 2), ',', -1)), '-'), '0')),
  `hp_wali` = COALESCE(NULLIF(`hp_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_hp`, ',', -1)), '-'), '0')),
  `pekerjaan_ayah` = COALESCE(NULLIF(`pekerjaan_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_pekerjaan`, ',', 1)), '-'), '0')),
  `pekerjaan_ibu` = COALESCE(NULLIF(`pekerjaan_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_pekerjaan`, ',', 2), ',', -1)), '-'), '0')),
  `pekerjaan_wali` = COALESCE(NULLIF(`pekerjaan_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_pekerjaan`, ',', -1)), '-'), '0')),
  `penghasilan_ayah` = COALESCE(NULLIF(`penghasilan_ayah`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_penghasilan`, ',', 1)), '-'), '0')),
  `penghasilan_ibu` = COALESCE(NULLIF(`penghasilan_ibu`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(`ortu_penghasilan`, ',', 2), ',', -1)), '-'), '0')),
  `penghasilan_wali` = COALESCE(NULLIF(`penghasilan_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_penghasilan`, ',', -1)), '-'), '0')),
  `alamat_orang_tua` = COALESCE(NULLIF(`alamat_orang_tua`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_alamat`, '|', 1)), '-'), '0')),
  `alamat_wali` = COALESCE(NULLIF(`alamat_wali`, ''), NULLIF(NULLIF(TRIM(SUBSTRING_INDEX(`ortu_alamat`, '|', -1)), '-'), '0'));
