<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['mahasiswa_required_fields'] = array(
	'utama' => array(
		array('name' => 'fakultas', 'label' => 'Fakultas Pilihan 1'),
		array('name' => 'gelombang', 'label' => 'Gelombang Pilihan 1'),
		array('name' => 'jurusan_pilihan', 'label' => 'Pilihan 1'),
		array('name' => 'gelombang_2', 'label' => 'Gelombang Pilihan 2'),
		array('name' => 'jurusan_pilihan2', 'label' => 'Pilihan 2'),
		array('name' => 'program', 'label' => 'Jalur Pendaftaran'),
		array('name' => 'jenis', 'label' => 'Jenis Pendaftaran'),
	),
	'lanjutan' => array(
		array('name' => 'nik', 'label' => 'NIK', 'rules' => 'required|min_length[16]|max_length[16]', 'step' => 'data_diri'),
		array('name' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'step' => 'data_diri'),
		array('name' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'step' => 'data_diri'),
		array('name' => 'tanggal_lahir', 'label' => 'Tanggal Lahir', 'step' => 'data_diri'),
		array('name' => 'email', 'label' => 'Email', 'rules' => 'required|valid_email', 'step' => 'data_diri'),
		array('name' => 'jk', 'label' => 'Jenis Kelamin', 'step' => 'data_diri'),
		array('name' => 'baju', 'label' => 'Ukuran Baju', 'step' => 'data_diri'),
		array('name' => 'agama', 'label' => 'Agama', 'step' => 'data_diri'),
		array('name' => 'kewarganegaraan', 'label' => 'Kewarganegaraan', 'step' => 'data_diri'),
		array('name' => 'alamat', 'label' => 'Alamat', 'step' => 'data_diri'),
		array('name' => 'kecamatan', 'label' => 'Kecamatan', 'step' => 'data_diri'),
		array('name' => 'kota', 'label' => 'Kabupaten/Kota', 'step' => 'data_diri'),
		array('name' => 'prov', 'label' => 'Provinsi', 'step' => 'data_diri'),
		array('name' => 'hp', 'label' => 'Nomor HP', 'step' => 'data_diri'),
		array('name' => 'ortu_nama', 'index' => 0, 'rule_name' => 'ortu_nama[0]', 'label' => 'Nama Ayah', 'step' => 'orang_tua'),
		array('name' => 'ortu_nama', 'index' => 1, 'rule_name' => 'ortu_nama[1]', 'label' => 'Nama Ibu', 'step' => 'orang_tua'),
		array('name' => 'ortu_nik', 'index' => 0, 'rule_name' => 'ortu_nik[0]', 'label' => 'NIK Ayah', 'rules' => 'required|min_length[16]|max_length[16]', 'step' => 'orang_tua'),
		array('name' => 'ortu_nik', 'index' => 1, 'rule_name' => 'ortu_nik[1]', 'label' => 'NIK Ibu', 'rules' => 'required|min_length[16]|max_length[16]', 'step' => 'orang_tua'),
		array('name' => 'sekolah_nama', 'label' => 'Asal Sekolah', 'condition' => 'mb', 'step' => 'data_diri'),
		array('name' => 'sekolah_jurusan', 'label' => 'Asal Jurusan', 'condition' => 'mb', 'step' => 'data_diri'),
		array('name' => 'nisn', 'label' => 'NISN', 'condition' => 'mb_non_pasca', 'step' => 'data_diri'),
		array('name' => 'ipk', 'label' => 'IPK', 'condition' => 'mb_pasca', 'step' => 'data_diri'),
		array('name' => 'tahun_lulus', 'label' => 'Tahun Lulus', 'rules' => 'required|min_length[4]|max_length[4]', 'condition' => 'mb', 'step' => 'data_diri'),
		array('name' => 'pindahan_namapt', 'label' => 'Asal Kampus', 'condition' => 'pindahan', 'step' => 'data_diri'),
		array('name' => 'pindahan_prodi', 'label' => 'Asal Program Studi', 'condition' => 'pindahan', 'step' => 'data_diri'),
	),
);
